name: Tests Runner
on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      ALLOWED_HOSTS: '*'
      SECRET_KEY: 'a secret for all'
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install OS packages
        run: sudo apt install python3-dev

      - name: Install Python packages
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run tests
        run: make coverage

      - name: Make manage.py executable
        run: chmod +x manage.py

      - name: Check deploy config
        run: ./manage.py check --deploy --fail-level WARNING
        env:
          DATABASE_URL: 'sqlite://:memory:'
          SECRET_KEY: 'zt(6jlr#oquxm2t%ryh#n+-72p^(3knbf&q$5x16#o%1im-s7!'
          SECURE_SSL_REDIRECT: 'on'
